app/assets/javascripts/authoring/taskStatus.js

Google Drive Opens in New Link

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js

Handoffs had some small pixels adjustments to be made to fix alignment. Nothing new in the code, all just changes to the routing. Included an old photo from master and new photo from the PR below. Nothing to actually test, but can play around to make sure they look ok.

Cleaned up routing of the handoffs

---

app/assets/javascripts/authoring/taskStatus.js

Changed default task color to grey

---

app/assets/javascripts/authoring/events.js

Removed event handlebars during runtime

---

app/assets/javascripts/authoring/events.js

Truncated duration text when the event block is too small the same way the title text is truncated
Fixes #182

Truncated duration text

---

app/assets/javascripts/authoring/chat_styling.js
app/assets/javascripts/authoring/events.js

Fix header height

---

app/assets/javascripts/authoring/events.js

Made not in progress worker task text dark grey

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/members.js
app/assets/javascripts/authoring/task_modal.js

Fix member tabs

---

app/assets/javascripts/authoring/awareness.js

Hid red box

---

app/controllers/members_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/send_confirmation_email.html.erb
app/views/user_mailer/send_confirmation_email.text.erb

I updated the text in the registration email to resolve the issue of Heroku taking a long time to send it (since it looked like spam). In addition to adding more text, I included the recipient's name in the email and signed it from "The Foundry Team." Review the text I added when merging to make sure it looks ok :)

Dr email text

---

app/assets/javascripts/authoring/timeline.js

I sent in #207 to separate the timeline into layers, but I realized that the layers were actually drawn in random order. This PR fixes that. The order is now
1. Grid layer
2. Selection layer
3. Event layer
4. Handoff layer
5. Collaboration layer

Ordered layers

---

app/views/flash_teams/_task_acceptance_content.html.erb
app/views/flash_teams/_task_acceptance_email_content.html.erb
app/views/flash_teams/_task_available_content.html.erb
app/views/flash_teams/_task_available_email_content.html.erb

Updated the text in the task available and task acceptance emails sent via the hiring portal

Dr hiring email updates

---

app/assets/javascripts/authoring/sidebar.js

This PR fixes the problem messing up the timestamps on the chat messages

Dr chat bug

---

app/assets/javascripts/authoring/interactions.js

I made several updates to the handoffs and collaborations: 
1) currently in master if you add a description to the handoffs or collabs and press save, it doesn't persist on refresh (we weren't calling updateStatus). This PR resolves this issue
2) Even if the descriptions were saving, they wouldn't appear in the textbox. Therefore, I updated the textbox to show the description if there is one: 
3) In worker mode and in runtime mode (i.e. when the team is in progress), the handoff and collab popover are in read only mode. NOTE: there is one bug I am aware of: if you are an author and you click on start team, the handoff/collab popover stays in edit mode until you refresh. I don't have the time to fix that right now but I don't think it is a big deal. 
4) I added a cancel button to the …

Dr handoff bug

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/gdrive.js
app/controllers/flash_teams_controller.rb
app/views/flash_teams/_project_status.html.erb

I THINK this pull request fixes most of the issues that occur when you try to duplicate a team. Below is a summary of the changes I made: 
1) When you duplicate a team that has members on it, the member link is automatically updated (i.e. it is not the same link as the original source team) 
2) A new google drive folder is created. This was not easy to do so please make sure you test it robustly to make sure I didn't mess anything up. Note that unlike before, the google drive project folder and folders for each of the tasks are now created when you click on the start button. Previously, the project folder was created when the first task was added to the timeline but that was quite problematic when it came to creating a new project folder post-duplication (and I don't think we really need …

Dr dup team fix

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/taskStatus.js
app/assets/javascripts/authoring/task_modal.js

This PR adds the ability to pause tasks. Below is how it works: 
1) I added a pause button to the modal. The pause button appears after you start a task: 
2) If you click on pause, four things happen:
a) the pause button changes to a resume button and the complete button is hidden: 
b) the timer on the task block is paused
c) the text on the sidebar in worker view says "Your task is paused" (in the dark blue color):
d) the task blocks turn a darker blue/grey. In author view, they are darker (opacity = 1). In worker view, they are more blueish/greyish (same color as author view but opacity = .6). Below are screenshots of blocks in author view and worker view: 
author view: 
worker view: 
3) When you click on the "resume task" button in the modal, the task should change back to the color it …

Dr pause event

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/members.js

Added tooltips to some of the event buttons.

Event tooltips

---

app/assets/javascripts/authoring/EntryManager.js
app/assets/javascripts/authoring/addRole.js
app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/docModal.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/eventslibrary.js
app/assets/javascripts/authoring/helper.js
app/assets/javascripts/authoring/members.js
app/assets/javascripts/authoring/notification_email.js
app/assets/javascripts/authoring/popovers.js
app/assets/javascripts/authoring/task_modal.js
app/assets/stylesheets/_animations.css.scss
app/assets/stylesheets/mock.css.scss

Fixes #257, #254
You can also drag into breadcrumbs

Can move members and folders into other folders

---

app/assets/javascripts/authoring/EntryManager.js

Fixed a bug preventing folders from being moved to other folders.

Fix folder move bug

---

app/assets/javascripts/authoring/addRole.js
app/assets/javascripts/authoring/awareness.js
app/assets/stylesheets/mock.css.scss

Can no longer add members when team starts

---

app/assets/javascripts/authoring/EntryManager.js
app/assets/javascripts/authoring/members.js

Created root folder at construction instead of on first add

---

app/assets/javascripts/authoring/eventTour.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/task_modal.js
app/assets/javascripts/authoring/tour.js

Text added to the final pane of the "event tour" (tour when worker logs in to Foundry) as well as the task modal that indicates that time for reading the previous materials is accounted for in the total work time. 
Definitely want to make sure this appears in a logical/appropriate place and that the text is clarifying for workers. Very open to phrasing suggestions here. 
Note that the extra time note on the task modal always appears on the read-only view of the modal. Even in author mode. This might be fixed later but for now makes sense since we may want the author to know this.

At read prompt

---

app/controllers/flash_teams_controller.rb
app/controllers/landings_controller.rb
app/controllers/members_controller.rb
app/views/flash_teams/_listQueue.html.erb
app/views/landings/view.html.erb

The hiring process now supports direct hiring (i.e. via a URL instead of the hiring queue). Pushed the latest code to Heroku for testing.

Kartik hiring documentation

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/taskStatus.js
app/assets/javascripts/authoring/task_modal.js
app/controllers/flash_teams_controller.rb
app/views/flash_teams/_task_available_content.html.erb
app/views/flash_teams/_task_modal.html.erb

This PR has a few updates to the pause feature as well as the event blocks/modals more generally: 
1) I removed the clock icon from the task blocks (closes issue #252)
2) When tasks are paused, I changed the color of the task to a lighter blue/grey (see screenshot under 3)
3) When a task is paused, the timer is replaced with the words "PAUSED" -- see below:
4) The pause button on the modal now says "Take a Break" instead of "Paused" -- see below: 
5) I updated the duration text on the modal so that instead of always saying "duration" and showing the original duration time, once a task has started (and when it is paused, delayed, etc.), it will say "Remaining" and show the remaining time followed by a "/" followed by the original duration time. Before a task is started, however, it will …

Dr pause updates

---

app/assets/javascripts/authoring/task_modal.js

fixed incorrect formatting of times on task modal for minutes < 0

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/helper.js
app/controllers/flash_teams_controller.rb
app/views/flash_teams/_left_sidebar.html.erb
app/views/flash_teams/_task_hiring_email.html.erb
config/routes.rb

This PR aims to resolve a few issues with how information was being stored in the flashTeamsJSON and the rails flash teams model more broadly. 
1) The flash team name is saved in three places (flash_team.name, flash_team.json (title attribute) and the flash team json saved in the status json (via the title attribute in the flash team json). Previously, when a team was renamed, it would only update flash_team.name, which caused certain features to use an outdated name (like the hiring panel). I updated the rename method in the controller to update all three of the names whenever the team name is updated. 
2) The initial data in the flashTeamsJSON didn't update until an event was added to the timeline (e.g., until there was a status object, which is created in the constructStatusObject …

Dr team name fix

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/eventslibrary.js
app/assets/javascripts/authoring/sidebar.js

This PR should properly update the timeline in all worker views and author view when an event is deleted in authoring mode and in editing mode. 
I also fixed the "onkeyup" error in the console that would always appear. When testing this PR, just make sure that the onkeyup error never appears in author or runtime mode in any of the views. 
To test this PR:
1) Create a new team (don't duplicate a team), add a role and open the worker view for that role  (you might want to add a few roles and open the timeline in a few worker views to be extra through)
2) With both views open, add an event (perhaps you should assign the worker to at least one of them to be thorough) 
3) Add a bunch of events and make sure all of the timelines update properly and that there are no errors in the console
4) …

Dr edit team fixes

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/eventDraw.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/gdrive.js
app/assets/stylesheets/mock.css.scss
app/views/flash_teams/_globals.html.erb
app/views/flash_teams/_header.html.erb
app/views/flash_teams/_left_sidebar.html.erb
app/views/flash_teams/_project_status.html.erb

This PR consists of a significant revamp of the google drive code and logic. I also added some minor awareness features/project status text to the sidebar. Sorry in advance for the long PR. I realize it is super long but please please please read it carefully and stress test this as much as possible to make sure I didn't introduce new bugs! Ultimately the goal is to make the google drive integration as solid and stable as possible but I worry that all of this new code/logic can also introduce additional problems. Hopefully that's not the case though :) 
**Relatively minor updates:**
When the project has not started yet, text appears under the google drive button indicating that the project has not yet started: 
When the google drive folder becomes active (e.g., the folder is successfully …

Dr gdrive folder fix

---

app/assets/javascripts/authoring/taskStatus.js
app/assets/javascripts/authoring/task_modal.js
app/assets/javascripts/authoring/training.js
app/assets/stylesheets/flash_teams.css.scss
app/views/workers/_new_content.html.erb

This PR should complete most of the changes needed for the pilot. I also made a few aesthetic changes to make the modals look better as well as a few usability fixes based on some things learned in previous pilots. Specifically, the updates I made are: 
1) For the field asking for the worker's oDesk profile URL in the panel registration form, it now asks for their oDesk/Elance profile URL (see screenshot under number 2 below)
2) The panel password field is now automatically filled out with the password provided when launching the training (which helps make sure they are providing a "valid" code when signing up). The panel password field in the registration form is now nor editable (e.g., it is read only) as shown in the screenshot below: 
3) I improved the appearance of the task modals. …

Dr pilot updates

---

app/assets/javascripts/authoring/training.js
app/views/flash_teams/_globals.html.erb
app/views/workers/_pc_modal.html.erb
app/views/workers/_worker_modal.html.erb
db/schema.rb

Re-created the videos, and modified the text for worker training
To Test: 
Launch worker training from localhost:3000/workers/register, go through the panel training, and watch each video. Check the content. In addition, make sure that things like skipping to the next page in the panel, or closing the training, don't leave videos still running.

Training Update

---

app/assets/javascripts/authoring/training.js
app/views/workers/_new_content.html.erb
app/views/workers/_register_content.html.erb
app/views/workers/_worker_modal.html.erb

This PR adds the ability to watch the training videos in refresher mode, which hides the registration form upon completion.

updated the panel training to support training video refresher

---

app/assets/javascripts/authoring/task_modal.js
app/views/flash_teams/_task_acceptance_email_content_landing.html.erb
app/views/flash_teams/_task_available_email_content.html.erb
app/views/landings/_task_acceptance_email_content_landing.html.erb

Text with HTML now renders properly in the task hiring portal. I also fixed a spacing issue on the task modal in edit mode.

Dr other fixes

---

app/assets/javascripts/application.js
app/views/flash_teams/_header.html.erb
app/views/layouts/application.html.erb

Commented out video conference code for now because it is causing a same origin error that is breaking other parts of Foundry.

removing the video conference feature for now

---

app/assets/javascripts/authoring/task_modal.js

I forgot to deal with the case in which additional inputs are added to a task. I decided to add those under handoff inputs. 
For example:

Dr modal input fix

---

app/assets/javascripts/authoring/notifications.js
app/assets/javascripts/authoring/sidebar.js

Added notifications (only for authors) when users sign on to Foundry. For now, I only show the authors these notifications since it is useful to know when the workers have signed on to Foundry. If we think they are useful, we can activate them for workers too. I also updated how the data is organized in firebase a bit and added activity logging for notifications.

Dr new notifs

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/docModal.js
app/assets/javascripts/authoring/eventDetails.js
app/assets/javascripts/authoring/eventDraw.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/gdrive.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/sidebar.js
app/assets/javascripts/authoring/taskStatus.js
app/assets/javascripts/authoring/task_modal.js
app/assets/stylesheets/custom.css
app/assets/stylesheets/mock.css.scss
app/views/flash_teams/_project_status.html.erb
app/views/flash_teams/_timeline.html.erb
db/schema.rb

Dr sidebar fixes

---

app/assets/javascripts/application.js
app/assets/javascripts/authoring/video_chat.js
app/views/flash_teams/_header.html.erb
app/views/layouts/application.html.erb

Fixed the icecomm videochat. Looks like the API key was outdated.

fixed the iceomm videochat

---

app/controllers/flash_teams_controller.rb
app/controllers/landings_controller.rb
app/controllers/members_controller.rb
app/views/flash_teams/_task_available_content.html.erb
app/views/landings/_error1.html.erb
app/views/landings/view.html.erb
app/views/members/register.html.erb

Updates
1. Replace should now work. More specifically, if uniq in the URL does not match the uniq corresponding to {team, task}, then it will throw an error.
2. Fixed the wording in the task available form to make it consistent with the email.
Problems
I was trying to clear out the queue when a member is replaced, but I can't understand the existing functionality of invite/reinvite. In fact, I'm not even sure where invite is called.

Kartik hiring changes

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/pauseTeam.js
app/assets/stylesheets/custom.css
app/controllers/flash_teams_controller.rb
app/mailers/user_mailer.rb
app/views/flash_teams/_header.html.erb
app/views/flash_teams/_project_status.html.erb
app/views/flash_teams/_request_edit_worker_modal.html.erb
app/views/flash_teams/edit.html.erb
app/views/user_mailer/send_edit_team_request_email.html.erb
config/routes.rb

This PR adds the request a change feature to allow workers to propose changes to the team. There are several different types of changes, which trigger different form fields to be displayed. When the request is submitted, an email gets sent out the project owner (e.g., the default email set on Foundry).

Dr worker edit team v2

---

app/assets/javascripts/authoring/awareness.js

Dr sidebar fix

---

app/assets/javascripts/authoring/sidebar.js

Fixed the chat timestamp problem that was causing the time stamps to all be the same.

Dr chat fixes

---

app/mailers/user_mailer.rb

ENV default email should now get bcc'ed even when other emails are bcc'ed

added env default email to bcc emails for specific mailers that use bcc

---

app/views/flash_teams/_starter_task_content.html.erb
app/views/flash_teams/_starter_task_email_content.html.erb
app/views/flash_teams/_task_available_email_content.html.erb
app/views/landings/_starter_task_acceptance_email_content_landing.html.erb

Fixed some typos in the starter task emails and cleaned up code a bit.

Dr starter task bug

---

app/assets/javascripts/authoring/pauseTeam.js
app/views/flash_teams/_request_edit_worker_modal.html.erb

Added the following options/forms to the request change modal: 
- "Add a Module"
- "Edit a Module"
- "Redo a Task"
Commented out the "Task Not Ready" choice from the dropdown in the request change modal (but left it in the sidebar for now).

Dr add request changes

---

app/assets/javascripts/authoring/pauseTeam.js
app/assets/javascripts/authoring/taskStatus.js

To test: open a team as a worker or superuser (PC), submit a request. It should post to the team's slack channel, as @mkim17 has requested.

pushing updates to slack when there's a change request

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/request_updates.js

This PR tries to speed up foundry by not calling drawEvents every 5 seconds in the initTimer function. For now, I call drawStartedEvents instead. I also removed all of the console logs.

Dr render bug

---

app/assets/javascripts/authoring/taskStatus.js

We keep splitting into new teams as Foundry breaks

Adding Trauma parts 3 and 4 to the Slack code

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/eventslibrary.js
app/assets/javascripts/authoring/members.js
app/assets/javascripts/authoring/odeskArrays.js
app/assets/javascripts/authoring/popovers.js
app/assets/javascripts/authoring/task_modal.js
app/assets/javascripts/authoring/tour.js
app/views/flash_teams/_task_acceptance_content.html.erb
app/views/flash_teams/_task_acceptance_email_content.html.erb
app/views/flash_teams/_task_acceptance_email_content_landing.html.erb
app/views/flash_teams/_task_available_content.html.erb
app/views/flash_teams/_task_available_email_content.html.erb
app/views/flash_teams/edit.html.erb
app/views/landings/_task_acceptance_email_content_landing.html.erb
app/views/landings/_task_waiting_email_content_landing.html.erb
app/views/user_mailer/_first_in_queue.html.erb
app/views/workers/_pc_modal.html.erb
app/views/workers/_worker_modal.html.erb

Made a few changes to the text on Foundry: 
1) Changed project coordinator labels to team lead
2) Removed the starter task text from hiring emails
3) Changed oDesk references to Upwork

Dr figures

---

Gemfile
Gemfile.lock
app/assets/javascripts/authoring/awareness.js
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/user.rb
app/views/users/login.html.erb
app/views/users/new.html.erb
db/migrate/20161112194141_add_password_digest_to_users.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

@junwonpk 
Depends on https://github.com/StanfordHCI/foundry/pull/375.
1. Registration with secure passwords
2. Log in with username and password

Secure authentication

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/docModal.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/pauseTeam.js
app/assets/javascripts/authoring/taskStatus.js
app/assets/javascripts/authoring/task_modal.js
app/assets/stylesheets/auth.css
app/assets/stylesheets/landing.css
app/controllers/application_controller.rb
app/controllers/flash_teams_controller.rb
app/controllers/users_controller.rb
app/views/flash_teams/_confirm_action.html.erb
app/views/flash_teams/_header.html.erb
app/views/flash_teams/_normal_header.html.erb
app/views/flash_teams/_project_overview_modal.html.erb
app/views/flash_teams/_request_edit_worker_modal.html.erb
app/views/flash_teams/_timeline.html.erb
app/views/flash_teams/edit.html.erb
app/views/flash_teams/index.html.erb
app/views/flash_teams/new.html.erb
app/views/users/login.html.erb
app/views/users/new.html.erb
app/views/welcome/index.html.erb
config/routes.rb

@junwonpk 
Depends on https://github.com/StanfordHCI/foundry/pull/376.
This PR introduces new styles for the following key aspects of Foundry:
1. Login page
2. Registration page
3. Flash teams list page
4. All buttons on Foundry, replacing default Bootstrap styles
The root path is changed to point to the login page now, instead of a page where the user has to choose between login and register. This helps remove one redundant user click.
These style changes are in service of a larger goal to create design consistency across the platform, in preparation for public usage. The overall design language we are going for is **minimalism**, which Foundry exemplifies even better after these changes are merged.

New CSS styles for design consistency

---

app/assets/stylesheets/auth.css
app/views/members/invited.html.erb

@jaypatelh Please review.
Registration page for onboarding workers now is styled in accordance with Foundry Author Login Page design.

Registration Page styling done

---

app/assets/javascripts/authoring/taskStatus.js
app/views/flash_teams/_header.html.erb

@jaypatelh removing green button

Request change button remove
