StanfordHCI/foundry

app/assets/stylesheets/hiring-panel.css.scss
app/controllers/flash_teams_controller.rb
app/views/flash_teams/_task_hiring_email.html.erb

All of the links on the left sidebar highlight properly to reflect current page (this PR updates the edit panels link and the tasks under "view other tasks", which previously didn't highlight). Resolves #29

Dr hiring fixes

---

app/controllers/application_controller.rb
app/controllers/flash_teams_controller.rb
app/controllers/users_controller.rb

This PR resolves the problems faced when trying to access the hiring portal and other pages that was causing a red "status nil" error page to appear. 
To test:
1) Copy the URLs for one of the team workflows (i.e. http://localhost:3000/flash_teams/21/edit) and some of the direct urls to the different hiring pages (i.e. http://localhost:3000/flash_teams/21/0/hire_form) and panel (i.e. http://localhost:3000/flash_teams/21/0/panels) and the other panel (http://localhost:3000/workers/index). 
2) Open an incognito window and try to access those pages -- you should automatically be redirected to the login page. After you login, it should redirect you to the page you were trying to access. Each time you want to test one of the pages, you need to make sure you logout (you can just go to …

Dr login fix

---

app/assets/javascripts/authoring/awareness.js
app/views/flash_teams/_globals.html.erb
lib/tasks/scheduler.rake

This PR moves the default_url, task_timer_interval, and timeline_interval variables to global ENV variables to make it easier to change their value for different dev and production environments in heroku.

Dr config vars

---

app/assets/javascripts/authoring/awareness.js

Quick fix. Didn't get rid of it, just set its display to none.

Hide the cursor

---

app/assets/javascripts/authoring/awareness.js

When the worker is not assigned to any tasks a recurring error shows in he console of the workers page. The error referred to this line of code in the awareness.js:
var ev = flashTeamsJSON["events"][getEventJSONIndex(currentUserEvents[0].id)];
I just added one line of code and checked the status messages on the side bar. If you want to make sure everything works, follow the instructions here:
https://github.com/StanfordHCI/foundry/pull/181

runtime bug: no task assigned to a worker.

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/sidebar.js
app/views/flash_teams/_project_status.html.erb

"The team is not started." in the sidebar tells the worker that the team is not started yet. 
The progress bar is commented out. We can bring it back when it works to replace and let it show up right after the team is started. 
Plus, I shortened the text  on the Google drive link in the sidebar. I removed the "Go to" part.

added "The team is not started." to the sidebar.

---

app/views/user_mailer/send_delayed_dri_not_responded.html.erb
app/views/user_mailer/send_delayed_dri_not_responded.text.erb
app/views/user_mailer/send_delayed_task_finished_email.html.erb
app/views/user_mailer/send_delayed_task_finished_email.text.erb
app/views/user_mailer/send_dri_on_delay_email.html.erb
app/views/user_mailer/send_dri_on_delay_email.text.erb
app/views/user_mailer/send_task_delayed_email.html.erb
app/views/user_mailer/send_task_delayed_email.text.erb

I updated the text in the HTML and TXT version of the following emails: 
send_delayed_dri_not_responded.html.erb
send_delayed_task_finished_email.html.erb
send_dri_on_delay_email.html.erb
send_task_delayed.html.erb
Please review the text in the emails and make sure it makes sense and that there are no typos. Also, on emails to the DRI I started them with "Hi @dri_role" -- ideally it should really be the DRI's name instead of their role but I wasn't sure how to access that. Let me know your thoughts / if you want to change it to the name. 
Also, one other random question, do we not send out emails anymore when the tasks are completed early? I noticed we have the code for it but I don't think you worked on it in this latest email update? Let me know! 
I think you can merge this into master …

Dr email notif text

---

app/assets/javascripts/authoring/events.js

Accidentally called `Math.floor` on fraction values less than 0, pushing the hours count down to -1. Fixed here.

Fixed delayed event timer

---

app/assets/javascripts/authoring/events.js

This PR (hopefully) resolves issue #171 
The event IDs are now generated using a timestamp from when they were created. Currently, this uses the local time on the user's machine. When teams are duplicated, the new team's tasks will have the original timestamps, which I think is fine since the important thing is for all of the tasks in a team to be unique. Eventually we might want to assign unique IDs to all tasks but I don't think that is important right now. Also, I could imagine cases in which it might be useful for duplicated tasks to have the same ID across teams for things like the event library (so that we only show one version of the same task). Just thinking out loud here. 
Anyway, when testing, try deleting tasks, creating handoffs, deleting handoffs, duplicating teams, running a …

event IDs are now based on the timestamp of when they were created

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/events.js

Should close #238. 
To check, draw a team with lots of handoffs. Try to delete an event and watch closely that the correct handoffs are deleted. Refresh the page and confirm nothing has changed. 
Check out code changes to see intuitively why this should fix it, if interested. There were redundant interaction deleting functions. Our function deleted items from the json, then called a function to delete items visually. The second function also tried to delete from the json.

At event del handoff

---

app/assets/javascripts/authoring/events.js

This bug fixes the problem that was preventing the gdrive upload button on the events from working in runtime mode (see #250)

fixed gdrive upload button bug

---

app/assets/javascripts/authoring/task_modal.js
app/assets/stylesheets/custom.css

Updated the "read only" version of the modal to make it easier to read and interpret. 
When it is populated and before it is started: 
When a task has just been created (i.e. no information has been entered yet): 
When a task is in progress [note how the status text in the top right of the modal updates to in progress]: 
Completion modal where worker answers the documentation question (this is the same as before, no changes were made): 
When some questions have been answered but modal hasn't been submitted yet: 
When task has been completed (note how the status text in the top right changes to completed):
When testing: 
1) Make sure modals appear correctly in both worker and author view.
2) Test creating tasks with different amounts of information entered. Make sure none of the formatting …

Dr task modal

---

app/assets/javascripts/authoring/task_modal.js

The inputs on the task modal are the outputs of immediately previous tasks and are linked to the Gdrive of that task. If an input is created for the current task and is not pulled from the previous tasks, it is linked to the Gdrive folder of the current event. 
Currently, the links don't work before the team is started because the Gdrive folders are created after the team is started. 
Create a team with inputs and outputs. Make sure the outputs of immediately previous tasks are the inputs of the task. If you add an input to a task using the task modal, make sure it is linked to the folder of the current event.

Inputs on the task modal are pulled from the previous tasks and are linked to the task Gdrive.

---

app/assets/javascripts/authoring/dependencies.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/task_modal.js
app/controllers/flash_teams_controller.rb
app/mailers/user_mailer.rb
app/views/flash_teams/_task_acceptance_content.html.erb
app/views/flash_teams/_task_acceptance_email_content.html.erb
app/views/flash_teams/_task_available_content.html.erb
app/views/flash_teams/_task_available_email_content.html.erb

The "review the inputs..." line doesn't show up when the task has no inputs. 
There are no weird line breaks any more. 
The outputs from the events in collaboration are added to the inputs of the current event. 
The inputs are in the hiring emails. 
I had to add "all_inputs" array each event's json. This array keeps all the inputs of each event in this format: [groupNum, event]. When ever a task modal is saved, all_inputs is updated for all events on the timeline. 
Could you check the parts of the code related to the hiring emails?  
I checked the hiring emails locally but I couldn't check them on heroku because the panels didn't show up! I am not sure why. This is the error I get:

Nr fix input link

---

app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js

Should close #120 
When an event is dragged out of range for a collaboration or handoff, the interaction slowly fades out and then is deleted. 
The reason we are doing this and not an alert dialog is that when you do an alert dialog, the drag doesn't stop and the event drags all over the screen when you close the alert. This is more elegant. 
Part of the review is to make sure this semantically makes sense for a user. If they drag the event out of range the interaction goes away and doesn't come back if you drag back into range. 
Just draw lots of events, collabs, and handoffs. Make sure the definition of "out of range" seems correct, things are actually deleting, and that they don't come back after refresh or anything else.

At int drag del

---

app/assets/javascripts/authoring/members.js
app/assets/javascripts/authoring/task_modal.js

start/complete/pause buttons now only show to members assigned to the task as well as PCs, clients and authors
Addresses #184 
This PR updates the task modals so that the start/complete/pause buttons only show to members assigned to the task as well as to all PCs, clients and authors. 
When testing: 
1) create a team, add events and assign members. Also add members to the team and assign them the role of "PC" and/or "client" 
2) It probably makes sense to assign multiple members to a task and make sure things still work properly
3) Start the team and open the team as a member, PC and client. Make sure to open the team as a couple of different members (assigned to different tasks). 
Make sure that the footer buttons show up correctly depending on the role. All clients and PCs (regardless …

task buttons in modal footer only appear to task members, PCs, clients and authors

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/members.js
app/assets/javascripts/authoring/sidebar.js
app/views/flash_teams/_left_sidebar.html.erb

The member role information should update in all views when changed. 
1) Previously, if the role (e.g., role name) was changed in author view, the worker would need to refresh the page in order to see the change in the left sidebar where it says "Welcome, WORKER NAME" followed by "Your Role Is: ROLE NAME" [the ROLE NAME is what should change] 
2) All role information should update on the event blocks when changed in author or edit mode (e.g., the role name, color, etc. on the events should update in realtime) 
3) If you change the "type" of a member from either worker to PC or from PC to worker, the roles widget on the left sidebar should appear and disappear in realtime, respectively. Previously, if you would change a member's role, the role widget would stay on the page or not appear …

Dr role updates

---

app/assets/javascripts/authoring/task_modal.js
app/views/flash_teams/_task_modal.html.erb

This PR changes the way inputs from handoffs and collaborations are displayed and described on the task modals. Specifically, I separated inputs from handoffs from inputs from collaborations and updated the text describing what to do with each of them. 
For example, a task that has inputs from handoffs and collaborations would look like this: 
If there is a handoff from a task without an output listed or if there is a collaboration with a task without any inputs, the name of the outputs on the task modal is replaced with either 'prior task results' or 'collaboration' -- Specifically, the task modal would look like this: 
If you click on the name of the task (under the linked deliverables) for the handoffs and collaborations on the task modal, it opens another task modal that has all of …

Dr collab modals

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/interactions.js

This pull request properly updates the interaction popovers for handoffs and collaborations. Previously, when you would start the team, the interaction popovers would remain in edit mode until you refreshed the page. Similarly, if you would click edit team, the popovers would remain in read only mode until you refreshed the page. Same thing would happen when you would click save team, the popovers would remain in read only mode until you refreshed the page. 
The popovers should now switch to read only mode right when you click start team, switch to edit mode right when you click edit team and switch back to read only mode when you click save team. 
Also, I attached the popover containers to ".container-fluid" instead of "#timeline-container" because they were getting squished if the event …

Dr int popovers fix

---

app/assets/javascripts/authoring/eventDetails.js
app/assets/javascripts/authoring/events.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/task_modal.js

Fixes: 
#332 
#330 
Specifically, I did the following: 
- added the configuration icon (which lets you duplicate, edit, view and delete event) to events that are 1 hour long (previously the icon would disappear). Now the icon only disappears when events are 45 mins or shorter.
- added a "Duplicate" task button to the footer of the task modal, which should duplicate the event and close the task modal when clicked on. The duplicate task button should only appear when the project hasn't been started or when the team is in edit mode. Workers should not be able to see the duplicate task button though (it should only be visible to authors, clients and PCs). 
- fixed the bug that caused the entire team to break if a task that had been started, delayed or paused was erased. Previously, the events …

Dr event fixes

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/taskStatus.js

Previously, the trackUpcomingEvent function was polling every few seconds to see if the text in the sidebar with the user's task status needed to be updated. This seemed extremely inefficient. For example, if you would open the inspector and hover over the code for the sidebar text, the code would flicker because ti was constantly being updated.
Therefore, in attempt to fix this, I commented out the interval code and instead called trackUpcomingEvent() at different points when the task status changed. For example, when the task is started, paused, resumed, completed, etc. I also added it to the renderEverything function.
When testing: 
1) Create a team, add tasks and assign them to at least one member
2) Open the team in the worker's view
3) Start the team 
4) In worker view, make sure …

removed polling for trackUpcomingEvent function 

---

app/controllers/flash_teams_controller.rb
config/routes.rb

Added clone feature, which copies over status information but replaces the member URLs. For now, the google drive folders copy over exactly and if you add tasks to team they are added to the ORIGINAL team. We will need to fix this soon.

added clone function

---

app/assets/javascripts/authoring/panels.js
app/controllers/flash_teams_controller.rb
app/controllers/landings_controller.rb
app/mailers/user_mailer.rb
app/views/flash_teams/_starter_task_content.html.erb
app/views/flash_teams/_starter_task_email_content.html.erb
app/views/flash_teams/_task_available_email_content.html.erb
app/views/flash_teams/_task_hiring_email.html.erb
app/views/flash_teams/_task_hiring_right_sidebar.html.erb
app/views/flash_teams/send_starter_task.html.erb
app/views/flash_teams/starter_task.html.erb
app/views/landings/_starter_task_acceptance_email_content_landing.html.erb
app/views/landings/_task_hiring_email.html.erb
app/views/landings/view.html.erb
app/views/user_mailer/send_starter_task_email.html.erb
app/views/workers/_filter_workers.html.erb
app/views/workers/_filter_workers_rightsidebar.html.erb
config/routes.rb

This PR adds the starter task feature so we can send different emails for starter tasks (compared to the task available emails). The landings controller and view page have also been updated to support the starter task content.

Dr starter task

---

app/assets/javascripts/authoring/taskStatus.js
app/controllers/flash_teams_controller.rb
app/views/flash_teams/_globals.html.erb

Please test and merge! We're moving team communication into Slack so that there's better coordination, but we want to keep mental models in sync with what's going on in Foundry.
I couldn't test with the live teams since that requires being hosted on foundry-app.herokuapp.com. (We only post to those Slack channels when the team ID matches.) So we'll need to do a little live testing once deployed to make sure the non-#flashteams channel integration works.
@dretelny @ato1120 @negarrahmati @tdoshi

slack integration for our three summer orgs

---

app/assets/javascripts/authoring/taskStatus.js

@mkim17 has created new teams "part 2" because Foundry is too slow. This is so that Slack continues to work for those teams.

adding new flash org team numbers for slack

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/request_updates.js
app/assets/javascripts/authoring/timeline.js

@dretelny 
This PR performs cleanup on the front-end JS code for Foundry in the following aspects.
Removes:
1. Polling for flash team updates every 50 seconds (a remnant from the pre-PubSub days)
2. Redundant comments
3. Old code, for example, code related to the moving cursor (from back in the day)
See rationale for no. 1 at https://docs.google.com/document/d/18BUztn4jd_5GFyIL5V1O6W2ppVkYBvL6UZ5f00dw83o/edit?usp=sharing.
Testing:
Change no. 1 was tested by creating a new flash team with 80 events (the exact number as the True Story 2 team that lagged) and 5 clients. It was observed that the new team was very responsive to the mouse in general between changes to events (like start, end etc), and also fully functional.
It was slow (as expected) when a Faye update was received and it …

Remove regular polling (Suggestion #1) and clean up redundant code

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/events.js

@jaypatelh
Creation of first event used to call updateStatus, whereas the subsequent events called updateEvent. This led to an error when the second event was created very soon after the creation of first event. 
Now, updateStatus (without the updateEvent part within it) is called at the creation of the team, not the first event, and the event creation calls updateEvent for all events including first one. Rapid creation of second event after the first (or the first event after the team's creation) does not cause internal server error anymore.

Junwon EventSpeed

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/pauseTeam.js

@junwonpk 
This PR disables editing an event when in review mode (of a pull request). This prevents a reviewer from modifying the timeline inadvertently.

Disable editing in review mode

---

app/assets/javascripts/authoring/awareness.js
app/assets/javascripts/authoring/interactions.js
app/assets/javascripts/authoring/pauseTeam.js
app/assets/javascripts/authoring/task_modal.js
app/views/flash_teams/_header.html.erb
app/views/flash_teams/_left_sidebar.html.erb
app/views/flash_teams/_project_status.html.erb
app/views/flash_teams/_task_acceptance_content.html.erb
app/views/flash_teams/_task_acceptance_email_content.html.erb
app/views/flash_teams/_task_acceptance_email_content_landing.html.erb
app/views/flash_teams/_timeline.html.erb
app/views/landings/_task_acceptance_email_content_landing.html.erb
app/views/landings/_task_waiting_email_content_landing.html.erb
app/views/user_mailer/_first_in_queue.html.erb

@junwonpk 
This PR fixes some of the salient issues with the worker view, as listed in [this Google Doc](https://docs.google.com/document/d/1BE_E0GmJfawgdZhEe2N66tswTxSuRgWd6TjzJF-uLrU/edit#).
Namely, the issues are:
- Clicking on links in the following section of event popover after filling it out leads to an undefined page: “Review the following tasks and deliverables, which are important for your task”
- ‘Deliverables’ link not working on event popover after team has started
- Worker view is a little messed up in the view
- Worker is provided option to suggest change to event -- take out? Furthermore, the link this sends to Slack for review is broken
- All of the following lead to the suggest change feature, which is broken
- Task Available text outdated: If you are still unfamiliar …

Fix salient issues with worker view

---

app/controllers/slack_controller.rb

@junwonpk 
On heroku, the `redirect_uri` of `http://localhost:3000/slack/auth` doesn't work. As per the Slack API, this field is optional anyway, so removing it. Will test on Heroku after this to see if it works.
@junwonpk Let me know if you know of a proper way to solve this issue.

Slack integration fix

---

app/controllers/landings_controller.rb
app/controllers/members_controller.rb
app/mailers/user_mailer.rb
app/views/members/invited.html.erb
app/views/user_mailer/send_team_link_email.html.erb
app/views/user_mailer/send_team_link_email.text.erb
config/routes.rb

@junwonpk cc: @mbernst 
This PR revamps the invite flow for new workers. It resolves a fatal issue regarding worker onboarding encountered during the foundry test during the last Flash meeting.
There are two main ways to invite a member:
1. Via the hiring portal (i.e. click on `Hire` on a task)
- does not require email confirmation because it is assumed the worker received the original request in their email anyway
- as soon as the worker accepts the job, the worker is automatically registered and redirected to the team page right away
- an email is sent to them with the link to the team (for future use)
2. Via the direct invite link (as obtained by clicking on a role on the left sidebar)
- this requires the worker to register and confirm their email to gain access to the team page
- like …

Revamp invite flow for new workers
